### PR TITLE
feat: apply styling to the console outputs and add order booked date field.

### PR DESCRIPTION
**Pull request by albertmir**
This aims to:
- Apply format and styles to the console outputs
- Also display the `orderBookedDate` field

### CODE REVIEW

**Comment by albertmir** [comment]
This is how it looks like:
Captura de pantalla 2024-09-03 a las 17 06 20

**Comment by niklaswa** [comment]
Looks awesome. Is this compatible with every operating system / console?
I've tried it with macOS, I'm always a bit afraid that something like this won't work in powershell on windows, for example 😄

**Comment by albertmir** [comment]
I'm not sure TBH 😅
I'm not a Python expert and I don't have Windows to test. I'm also on Mac

**Comment by albertmir** [comment]
After asking for it on [the spanish forum](https://foro.clubtesla.es/index.php?topic=10545.1695#forum), some people tested it on both Windows and Linux and they said it works fine for them. Sounds good enough? 😉

**Comment by niklaswa** [comment]
Alright, looks good, thank you!!

If there are some problems with the styling in the future, we can invastigate further 😄

**Comment by albertmir** [comment]
Perfect. Thanks!! :)

**Pull request merged**
